function [FileName,time] = importImageTimestamps(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [FILENAME,TIME] = IMPORTFILE(FILENAME) Reads data from text file
%   FILENAME for the default selection.
%
%   [FILENAME,TIME] = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data
%   from rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   [FileName,time] = importfile('20150618_104559_AUTOSWEEP.txt',3, 14);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2015/06/22 21:27:51

%% Initialize variables.
delimiter = '\t';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Format string for each line of text:
%   column1: text (%s)
%	column2: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Count number of lines
if (isunix) %# Linux, mac
    [~, result] = system( ['wc -l ', '"', filename, '"']);
    result = strsplit(result,' ');
    numlines = str2num(result{2});

elseif (ispc) %# Windows
    numlines = str2num( perl('countlines.pl', filename) );
end
endRow = numlines - 1;

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
FileName = dataArray{:, 1};
time = dataArray{:, 2};


end